class ZCL_ZRC_ANALYSIS_DPC_EXT definition
  public
  inheriting from ZCL_ZRC_ANALYSIS_DPC
  create public .

public section.

  methods /IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_STREAM
    redefinition .
protected section.
private section.
ENDCLASS.



CLASS ZCL_ZRC_ANALYSIS_DPC_EXT IMPLEMENTATION.


METHOD /iwbep/if_mgw_appl_srv_runtime~get_stream.

  DATA: ls_key      TYPE /iwbep/s_mgw_name_value_pair,
        lv_target   TYPE string,
        lv_zip_xstr TYPE xstring,
        ls_stream   TYPE ty_s_media_resource.

  DATA: lo_mc TYPE REF TO /iwbep/if_message_container.

  "ZIP builder
  DATA: lo_zip   TYPE REF TO cl_abap_zip,
        lv_text  TYPE string,
        lv_txt_x TYPE xstring.

  "Local macro to raise business error with visible text
  DEFINE raise_busi_error.
    CLEAR lo_mc.
    TRY.
        lo_mc = mo_context->get_message_container( ).
      CATCH cx_root.
    ENDTRY.

    IF lo_mc IS BOUND.
      lo_mc->add_message_text_only(
        iv_msg_type = 'E'
        iv_msg_text = &1 ).
      RAISE EXCEPTION TYPE /iwbep/cx_mgw_busi_exception
        EXPORTING
          message_container = lo_mc.
    ELSE.
      RAISE EXCEPTION TYPE /iwbep/cx_mgw_busi_exception
        EXPORTING
          message = &1.
    ENDIF.
  END-OF-DEFINITION.

  "1) Key read
  CLEAR ls_key.
  READ TABLE it_key_tab INTO ls_key WITH KEY name = 'TargetSystem'.
  IF sy-subrc <> 0 OR ls_key-value IS INITIAL.
    raise_busi_error 'TargetSystem is required'.
  ENDIF.
  lv_target = ls_key-value.

  "2) Build ZIP in memory (valid ZIP)
  CREATE OBJECT lo_zip.

  CONCATENATE 'Readiness ZIP generated by OData. TargetSystem=' lv_target
         INTO lv_text.

  CALL FUNCTION 'SCMS_STRING_TO_XSTRING'
    EXPORTING
      text   = lv_text
    IMPORTING
      buffer = lv_txt_x
    EXCEPTIONS
      failed = 1
      OTHERS = 2.

  IF sy-subrc <> 0 OR lv_txt_x IS INITIAL.
    raise_busi_error 'SCMS_STRING_TO_XSTRING failed'.
  ENDIF.

  lo_zip->add(
    name    = 'README.txt'
    content = lv_txt_x ).

  lo_zip->save( RECEIVING zip = lv_zip_xstr ).

  IF lv_zip_xstr IS INITIAL.
    raise_busi_error 'ZIP creation failed (empty xstring)'.
  ENDIF.

  "3) Stream response (direct ZIP xstring)
  ls_stream-mime_type = 'application/zip'.
  ls_stream-value     = lv_zip_xstr.

  copy_data_to_ref(
    EXPORTING is_data = ls_stream
    CHANGING  cr_data = er_stream ).

ENDMETHOD.
ENDCLASS.
